services:
  mysql:
    container_name: mysql_container
    image: mysql:latest
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    restart: unless-stopped

  adminer:
    container_name: adminer_container
    image: adminer:latest
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      - mysql

volumes:
  mysql_data:
